#!/usr/bin/env python3
"""Regenerates src/unicode_tables.zig (Unicode letter/number/whitespace ranges) from Python's unicodedata."""
import unicodedata
def ranges(pred):
    out=[]; start=None
    for cp in range(0x110000):
        ok=pred(cp)
        if ok and start is None: start=cp
        if not ok and start is not None: out.append((start,cp-1)); start=None
    if start is not None: out.append((start,0x10FFFF))
    return out
L=ranges(lambda c: unicodedata.category(chr(c)).startswith('L'))
N=ranges(lambda c: unicodedata.category(chr(c)).startswith('N'))
S=ranges(lambda c: chr(c).isspace())
def emit(name, rs):
    lines=[f"pub const {name} = [_]Range{{"]
    for a,b in rs: lines.append(f"    .{{ .lo = 0x{a:X}, .hi = 0x{b:X} }},")
    lines.append("};")
    return "\n".join(lines)
src = "//! Generated by tools/gen_unicode.py from Python's unicodedata (Unicode %s). Do not edit.\n" % unicodedata.unidata_version
src += "pub const Range = struct { lo: u21, hi: u21 };\n\n"
src += emit("letters", L) + "\n\n" + emit("numbers", N) + "\n\n" + emit("whitespace", S) + "\n"
open("src/unicode_tables.zig","w").write(src)
