#!/usr/bin/env python3
"""Regenerates src/unicode_tables.zig: the Unicode letter/number/whitespace/case/mark
ranges from Python's unicodedata, the Han script from the `regex` package (which is
what the tiktoken pre-tokeniser's `\\p{Han}` means), and the per-code-point "fold"
mapping (NFKD, then drop every combining mark, then lowercase every char) that
DeepSeek-V4.1 uses to build the compressed token map of its engram hash layers.
Hangul syllables fold algorithmically and are not in the table. Also the NFKC of
every single code point that NFKC (and NFC) changes, for the tokenizer normalizers."""
import unicodedata
import regex
def ranges(pred):
    out=[]; start=None
    for cp in range(0x110000):
        ok=pred(cp)
        if ok and start is None: start=cp
        if not ok and start is not None: out.append((start,cp-1)); start=None
    if start is not None: out.append((start,0x10FFFF))
    return out
L=ranges(lambda c: unicodedata.category(chr(c)).startswith('L'))
N=ranges(lambda c: unicodedata.category(chr(c)).startswith('N'))
ND=ranges(lambda c: unicodedata.category(chr(c)) == 'Nd')
PS=ranges(lambda c: unicodedata.category(chr(c))[0] in 'PS')
PU=ranges(lambda c: unicodedata.category(chr(c))[0] == 'P')
S=ranges(lambda c: chr(c).isspace())
U=ranges(lambda c: unicodedata.category(chr(c)) in ('Lu','Lt'))
LL=ranges(lambda c: unicodedata.category(chr(c)) == 'Ll')
M=ranges(lambda c: unicodedata.category(chr(c)).startswith('M'))
han_re=regex.compile(r'\p{Han}')
H=ranges(lambda c: han_re.match(chr(c)) is not None)
def emit(name, rs):
    lines=[f"pub const {name} = [_]Range{{"]
    for a,b in rs: lines.append(f"    .{{ .lo = 0x{a:X}, .hi = 0x{b:X} }},")
    lines.append("};")
    return "\n".join(lines)
def fold(cp):
    s=unicodedata.normalize('NFKD',chr(cp))
    # tokenizers' StripAccents drops every combining mark (Mn, Mc and Me), not
    # only the nonspacing ones: Indic vowel signs are Mc.
    s=''.join(x for x in s if not unicodedata.category(x).startswith('M'))
    return ''.join(x.lower() for x in s)
entries=[(cp,fold(cp)) for cp in range(0x110000) if not (0xAC00<=cp<=0xD7A3) and fold(cp)!=chr(cp)]
runs=[]; drops=[]; multi=[]
i=0
while i<len(entries):
    cp,s=entries[i]
    if len(s)==1:
        delta=ord(s)-cp; j=i+1
        while j<len(entries) and entries[j][0]==entries[j-1][0]+1 and len(entries[j][1])==1 and ord(entries[j][1])-entries[j][0]==delta: j+=1
        runs.append((cp,entries[j-1][0],delta)); i=j
    elif len(s)==0:
        j=i+1
        while j<len(entries) and entries[j][0]==entries[j-1][0]+1 and len(entries[j][1])==0: j+=1
        drops.append((cp,entries[j-1][0])); i=j
    else:
        multi.append((cp,s)); i+=1
def zstr(s):
    return '"' + ''.join('\\x%02x' % b for b in s.encode()) + '"'
src = "//! Generated by tools/gen_unicode.py from Python's unicodedata (Unicode %s; the Han script from regex %s). Do not edit.\n" % (unicodedata.unidata_version, regex.__version__)
src += "pub const Range = struct { lo: u21, hi: u21 };\n\n"
src += emit("letters", L) + "\n\n" + emit("numbers", N) + "\n\n" + emit("whitespace", S) + "\n\n"
src += "/// `Lu` and `Lt`.\n" + emit("upper", U) + "\n\n" + "/// `Ll`.\n" + emit("lower", LL) + "\n\n"
src += "/// `P` (punctuation).\n" + emit("punctuation", PU) + "\n\n" + "/// `P` and `S` (punctuation and symbols).\n" + emit("punct_symbols", PS) + "\n\n" + "/// `Nd` (decimal digits).\n" + emit("decimal_digits", ND) + "\n\n" + "/// `M` (combining marks).\n" + emit("marks", M) + "\n\n" + "/// Script=Han (`\\p{Han}`).\n" + emit("han", H) + "\n\n"
src += "/// Code points `lo..hi` whose fold is the single code point `cp + delta`.\n"
src += "pub const FoldRun = struct { lo: u21, hi: u21, delta: i32 };\n"
src += "pub const fold_runs = [_]FoldRun{\n" + "\n".join(f"    .{{ .lo = 0x{a:X}, .hi = 0x{b:X}, .delta = {d} }}," for a,b,d in runs) + "\n};\n\n"
src += "/// Code points whose fold is empty (combining marks).\n"
src += emit("fold_drop", drops) + "\n\n"
src += "/// Code points whose fold is several code points (UTF-8).\n"
src += "pub const FoldMulti = struct { cp: u21, out: []const u8 };\n"
src += "pub const fold_multi = [_]FoldMulti{\n" + "\n".join(f"    .{{ .cp = 0x{cp:X}, .out = {zstr(s)} }}," for cp,s in multi) + "\n};\n"
# NFKC of each code point on its own (composition across code points, e.g. a
# letter followed by a combining accent, is not applied).
nfkc=[(cp,unicodedata.normalize('NFKC',chr(cp))) for cp in range(0x110000) if not (0xD800<=cp<=0xDFFF) and unicodedata.normalize('NFKC',chr(cp))!=chr(cp)]
nfc=[(cp,unicodedata.normalize('NFC',chr(cp))) for cp in range(0x110000) if not (0xD800<=cp<=0xDFFF) and unicodedata.normalize('NFC',chr(cp))!=chr(cp)]
src += "\n/// NFC of single code points, for the code points it changes (singletons and\n/// composition exclusions; sorted by `cp`).\n"
src += "pub const nfc_map = [_]FoldMulti{\n" + "\n".join(f"    .{{ .cp = 0x{cp:X}, .out = {zstr(s)} }}," for cp,s in nfc) + "\n};\n"
src += "\n/// NFKC of single code points, for the code points it changes (sorted by `cp`).\n"
src += "pub const nfkc_map = [_]FoldMulti{\n" + "\n".join(f"    .{{ .cp = 0x{cp:X}, .out = {zstr(s)} }}," for cp,s in nfkc) + "\n};\n"
# Canonical composition, for the NFKC normalizer: primary composites (pairs
# whose NFC is one code point; composition exclusions and Hangul, which
# composes algorithmically, are left out) and the non-zero combining classes.
pairs=[]
for cp in range(0x110000):
    if 0xD800<=cp<=0xDFFF or 0xAC00<=cp<=0xD7A3: continue
    d=unicodedata.decomposition(chr(cp))
    if not d or d.startswith('<'): continue
    parts=[int(x,16) for x in d.split()]
    if len(parts)==2 and unicodedata.normalize('NFC',chr(parts[0])+chr(parts[1]))==chr(cp):
        pairs.append((parts[0],parts[1],cp))
pairs.sort()
ccc=[(cp,unicodedata.combining(chr(cp))) for cp in range(0x110000) if not (0xD800<=cp<=0xDFFF) and unicodedata.combining(chr(cp))]
src += "\n/// Primary composites `first + second -> out`, sorted by (first, second).\n"
src += "pub const Compose = struct { first: u21, second: u21, out: u21 };\n"
src += "pub const compose_pairs = [_]Compose{\n" + "\n".join(f"    .{{ .first = 0x{a:X}, .second = 0x{b:X}, .out = 0x{c:X} }}," for a,b,c in pairs) + "\n};\n"
src += "\n/// Non-zero canonical combining classes, sorted by `cp`.\n"
src += "pub const Ccc = struct { cp: u21, ccc: u8 };\n"
src += "pub const combining_class = [_]Ccc{\n" + "\n".join(f"    .{{ .cp = 0x{cp:X}, .ccc = {c} }}," for cp,c in ccc) + "\n};\n"
open("src/unicode_tables.zig","w").write(src)
