return {
  model_type = "biogpt",
  llama_cpp = nil,
  verified = true,
  notes = "fixture: learned positions with offset 2, sqrt(hidden) embedding scale, output_projection head. BioGPT.",
  norm = "layer",
  default_norm_eps = 1e-12,
  positional = "learned",
  mlp = "dense",
  activation = "gelu",
  attention_bias = true,
  names = {
    prefixes = { "biogpt.", "model.", "" },
    pos_embed = "{p}embed_positions.weight",
    final_norm = "{p}layer_norm.weight",
    lm_head = { "output_projection.weight", "lm_head.weight" },
    input_norm = { "self_attn_layer_norm.weight" },
    pre_ff_norm = "final_layer_norm.weight",
    o = "self_attn.out_proj.weight",
    gate = false,
    up = "fc1.weight",
    down = "fc2.weight",
  },
  hook = "biogpt",
}
