return {
  model_type = "bloom",
  llama_cpp = "bloom",
  verified = true,
  notes = "fixture: ALiBi, embedding LayerNorm, head-interleaved fused qkv with biases.",
  norm = "layer",
  positional = "alibi",
  qkv = "heads_interleaved",
  mlp = "dense",
  activation = "gelu_tanh",
  attention_bias = true,
  tie_word_embeddings = true,
  names = {
    prefixes = { "transformer.", "" },
    embed = "{p}word_embeddings.weight",
    embed_norm = "{p}word_embeddings_layernorm.weight",
    final_norm = "{p}ln_f.weight",
    layer = "{p}h.{i}.",
    q = false,
    k = false,
    v = false,
    qkv = "self_attention.query_key_value.weight",
    o = "self_attention.dense.weight",
    gate = false,
    up = "mlp.dense_h_to_4h.weight",
    down = "mlp.dense_4h_to_h.weight",
  },
}
