return {
  model_type = "chatglm",
  llama_cpp = "chatglm",
  chat = "glm4",
  verified = true,
  notes = "fixture: ChatGLM3 / GLM-4 (remote-code layout): concatenated query_key_value with bias, fused dense_h_to_4h, interleaved half rotary with rope_ratio, output_layer.",
  rope_style = "gptj",
  qkv = "concat",
  mlp = "gated_fused",
  attention_bias = true,
  names = {
    prefixes = { "transformer." },
    embed = "{p}embedding.word_embeddings.weight",
    final_norm = "{p}encoder.final_layernorm.weight",
    lm_head = { "transformer.output_layer.weight" },
    layer = "{p}encoder.layers.{i}.",
    q = false,
    k = false,
    v = false,
    qkv = "self_attention.query_key_value.weight",
    o = "self_attention.dense.weight",
    gate = false,
    up = false,
    gate_up = "mlp.dense_h_to_4h.weight",
    down = "mlp.dense_4h_to_h.weight",
  },
  hook = "chatglm",
}
