return {
  model_type = "deepseek_v4",
  llama_cpp = nil,
  chat = "deepseek",
  verified = true,
  notes = "fixture: hyper-connections (hc_mult streams, Sinkhorn-mixed), low-rank q with unweighted head norm, shared-KV sliding attention with sinks and inverse-roped output, grouped output projection, CSA (overlapping pooled windows; Lightning Indexer as dense: exact while every reachable entry fits index_topk) and HCA branches with their own rope, sqrtsoftplus MoE with correction bias, hash-routed (tid2eid) layers, clamped SwiGLU, shared expert, MTP tensors passed through. The released checkpoints (DeepSeek's own tensor names, FP8 with ue8m0 block scales, FP4 e2m1 experts) are renamed and dequantised on load; DeepSeek-V4-Flash's first four layers (sliding, CSA and HCA attention, hash and learned routing) match transformers in float32 on the real weights.",
  rope_style = "gptj",
  names = {
    o = "self_attn.o_b_proj.weight",
    sinks = "self_attn.sinks",
    q_a = "self_attn.q_a_proj.weight",
    q_a_norm = "self_attn.q_a_norm.weight",
    q_b = "self_attn.q_b_proj.weight",
    kv_a = "self_attn.kv_proj.weight",
    kv_a_norm = "self_attn.kv_norm.weight",
    router_correction_bias = "mlp.gate.e_score_correction_bias",
    shared_expert = "mlp.shared_experts.",
  },
  hook = "deepseek_v4",
}
