return {
  model_type = "falcon",
  aliases = { "RefinedWebModel" },
  llama_cpp = "falcon",
  verified = true,
  notes = "fixture: multi-query fused qkv (7B layout), parallel attention with one LayerNorm. The 40B/180B grouped layout with ln_attn/ln_mlp and the ALiBi variant are implemented but unverified. Falcon-H1 is the `falcon_h1` entry.",
  norm = "layer",
  parallel_residual = true,
  qkv = "concat",
  mlp = "dense",
  activation = "gelu",
  tie_word_embeddings = true,
  names = {
    prefixes = { "transformer.", "" },
    embed = "{p}word_embeddings.weight",
    final_norm = "{p}ln_f.weight",
    layer = "{p}h.{i}.",
    input_norm = { "input_layernorm.weight", "ln_attn.weight" },
    mlp_norm = "ln_mlp.weight",
    q = false,
    k = false,
    v = false,
    qkv = "self_attention.query_key_value.weight",
    o = "self_attention.dense.weight",
    gate = false,
    up = "mlp.dense_h_to_4h.weight",
    down = "mlp.dense_4h_to_h.weight",
  },
  hook = "falcon",
}
