return {
  model_type = "gemma4",
  aliases = { "gemma4_text", "gemma4_unified", "gemma4_unified_text" },
  llama_cpp = "gemma4",
  chat = "gemma4",
  verified = true,
  notes = "fixture (text): global layers with their own head size and KV heads (global_head_dim / per_layer_config), proportional rope on global layers and a local base on sliding ones, keys reused as values (attention_k_eq_v), KV-shared layers, weightless value norm, unit attention scale, per-layer input embeddings, layer_scalar, double-wide MLPs on shared layers. The gemma4 image/audio wrapper runs its text config; the towers pass through exports untouched. The MoE block of gemma-4-26B-A4B (enable_moe_block) is not implemented.",
  activation = "gelu_tanh",
  tie_word_embeddings = true,
  embed_scale_sqrt = true,
  qk_norm = "head",
  names = {
    post_attn_norm = "post_attention_layernorm.weight",
    pre_ff_norm = "pre_feedforward_layernorm.weight",
    post_ff_norm = "post_feedforward_layernorm.weight",
    q_norm = "self_attn.q_norm.weight",
    k_norm = "self_attn.k_norm.weight",
    ple_embed = "{p}embed_tokens_per_layer.weight",
    ple_proj = "{p}per_layer_model_projection.weight",
    ple_proj_norm = "{p}per_layer_projection_norm.weight",
    ple_gate = "per_layer_input_gate.weight",
    ple_out = "per_layer_projection.weight",
    ple_norm = "post_per_layer_input_norm.weight",
    layer_scale = "layer_scalar",
  },
  hook = "gemma4",
}
