return {
  model_type = "gemma3n",
  aliases = { "gemma3n_text" },
  llama_cpp = "gemma3n",
  chat = "gemma",
  verified = true,
  notes = "fixture (text): AltUp residual streams (predict / correct, magnitude-matched embed and unembed projections), Laurel blocks, per-layer input embeddings, KV-shared layers, weightless value norm, unit attention scale, gaussian-top-k gate sparsity, sliding layers with a local rope base, final logit softcapping. The gemma3n image/audio wrapper runs its text config; the towers pass through exports untouched.",
  activation = "gelu_tanh",
  tie_word_embeddings = true,
  embed_scale_sqrt = true,
  qk_norm = "head",
  names = {
    post_attn_norm = "post_attention_layernorm.weight",
    pre_ff_norm = "pre_feedforward_layernorm.weight",
    post_ff_norm = "post_feedforward_layernorm.weight",
    q_norm = "self_attn.q_norm.weight",
    k_norm = "self_attn.k_norm.weight",
    ple_embed = "{p}embed_tokens_per_layer.weight",
    ple_proj = "{p}per_layer_model_projection.weight",
    ple_proj_norm = "{p}per_layer_projection_norm.weight",
    ple_gate = "per_layer_input_gate.weight",
    ple_out = "per_layer_projection.weight",
    ple_norm = "post_per_layer_input_norm.weight",
    altup_proj = "{p}altup_projections.{e}.weight",
    altup_unembed = "{p}altup_unembed_projections.{e}.weight",
    altup_router = "altup.modality_router.weight",
    altup_router_norm = "altup.router_norm.weight",
    altup_predict = "altup.prediction_coefs.weight",
    altup_correct = "altup.correction_coefs.weight",
    altup_scale = "altup.correct_output_scale",
    laurel_l = "laurel.linear_left.weight",
    laurel_r = "laurel.linear_right.weight",
    laurel_norm = "laurel.post_laurel_norm.weight",
  },
  hook = "gemma3n",
}
