return {
  model_type = "glm5_next",
  aliases = { "glm5_next_text" },
  llama_cpp = nil,
  chat = "glm4",
  verified = true,
  notes = "fixture: GLM-5.3-Flash text config under the multimodal wrapper: manifold-constrained hyper-connections collapsed by an unweighted mean, Kimi Delta Attention layers with the safe lower-bound forget gate, NoPE MLA layers behind a k-pool DSA indexer with full and shared indexer types (run as dense: exact while every complete pool fits index_topk, longer prompts refused), sigmoid MoE with correction bias, top-2 group scores, floored renormalisation, routed_scaling_factor and shared experts, clamped SwiGLU in experts, shared experts and dense layers, mlp_layer_types. Vision and indexer tensors pass through exports untouched.",
  default_norm_eps = 1e-5,
  linear = "kda",
  names = {
    lin_b = "self_attn.b_proj.weight",
    lin_q = "self_attn.q_proj.weight",
    lin_k = "self_attn.k_proj.weight",
    lin_v = "self_attn.v_proj.weight",
    lin_f_a = { "self_attn.forget_gate.f_a_proj.weight", "self_attn.f_a_proj.weight" },
    lin_f_b = { "self_attn.forget_gate.f_b_proj.weight", "self_attn.f_b_proj.weight" },
    lin_g_a = "self_attn.g_a_proj.weight",
    lin_g_b = "self_attn.g_b_proj.weight",
    lin_conv = "self_attn.conv1d.weight",
    lin_conv_split = { "self_attn.q_conv1d.weight", "self_attn.k_conv1d.weight", "self_attn.v_conv1d.weight" },
    lin_dt_bias = { "self_attn.forget_gate.dt_bias", "self_attn.dt_bias" },
    lin_a_log = { "self_attn.forget_gate.A_log", "self_attn.A_log" },
    lin_norm = "self_attn.o_norm.weight",
    lin_out = "self_attn.o_proj.weight",
    q_a = "self_attn.q_a_proj.weight",
    q_a_norm = "self_attn.q_a_layernorm.weight",
    q_b = "self_attn.q_b_proj.weight",
    kv_a = "self_attn.kv_a_proj_with_mqa.weight",
    kv_a_norm = "self_attn.kv_a_layernorm.weight",
    kv_b = "self_attn.kv_b_proj.weight",
    router_correction_bias = "mlp.gate.e_score_correction_bias",
    shared_expert = "mlp.shared_experts.",
  },
  hook = "glm5_next",
}
