return {
  model_type = "gpt2",
  llama_cpp = "gpt2",
  verified = true,
  notes = "fixture: Conv1D ([in][out]) weights transposed on load and export, learned positions (wpe), fused c_attn, gelu_new, tied lm_head.",
  norm = "layer",
  positional = "learned",
  qkv = "concat",
  mlp = "dense",
  conv1d = true,
  activation = "gelu_tanh",
  attention_bias = true,
  tie_word_embeddings = true,
  names = {
    prefixes = { "transformer.", "" },
    embed = "{p}wte.weight",
    pos_embed = "{p}wpe.weight",
    final_norm = "{p}ln_f.weight",
    layer = "{p}h.{i}.",
    input_norm = { "ln_1.weight" },
    pre_ff_norm = "ln_2.weight",
    q = false,
    k = false,
    v = false,
    qkv = "attn.c_attn.weight",
    o = "attn.c_proj.weight",
    gate = false,
    up = "mlp.c_fc.weight",
    down = "mlp.c_proj.weight",
  },
}
