return {
  model_type = "gpt_bigcode",
  llama_cpp = "starcoder",
  verified = true,
  notes = "fixture: multi-query c_attn (nn.Linear layout), learned positions, LayerNorm biases. StarCoder 1 / SantaCoder.",
  norm = "layer",
  positional = "learned",
  qkv = "concat",
  mlp = "dense",
  activation = "gelu_tanh",
  attention_bias = true,
  tie_word_embeddings = true,
  names = {
    prefixes = { "transformer.", "" },
    embed = "{p}wte.weight",
    pos_embed = "{p}wpe.weight",
    final_norm = "{p}ln_f.weight",
    layer = "{p}h.{i}.",
    input_norm = { "ln_1.weight" },
    pre_ff_norm = "ln_2.weight",
    q = false,
    k = false,
    v = false,
    qkv = "attn.c_attn.weight",
    o = "attn.c_proj.weight",
    gate = false,
    up = "mlp.c_fc.weight",
    down = "mlp.c_proj.weight",
  },
  hook = "gpt_bigcode",
}
