return {
  model_type = "gpt_neo",
  llama_cpp = "gptneo",
  verified = true,
  notes = "fixture: learned positions, unscaled attention logits, alternating global and window_size local layers (attention_types), c_fc/c_proj MLP. GPT-Neo 1.3B/2.7B.",
  norm = "layer",
  positional = "learned",
  mlp = "dense",
  activation = "gelu_tanh",
  tie_word_embeddings = true,
  names = {
    prefixes = { "transformer.", "" },
    embed = "{p}wte.weight",
    pos_embed = "{p}wpe.weight",
    final_norm = "{p}ln_f.weight",
    layer = "{p}h.{i}.",
    input_norm = { "ln_1.weight" },
    pre_ff_norm = "ln_2.weight",
    q = "attn.attention.q_proj.weight",
    k = "attn.attention.k_proj.weight",
    v = "attn.attention.v_proj.weight",
    o = "attn.attention.out_proj.weight",
    gate = false,
    up = "mlp.c_fc.weight",
    down = "mlp.c_proj.weight",
  },
  hook = "gpt_neo",
}
