return {
  model_type = "gpt_neox",
  llama_cpp = "gptneox",
  verified = true,
  notes = "fixture: head-interleaved query_key_value, parallel residual, rotary_pct, LayerNorm biases, embed_out. Pythia / GPT-NeoX.",
  norm = "layer",
  parallel_residual = true,
  qkv = "heads_interleaved",
  mlp = "dense",
  activation = "gelu",
  attention_bias = true,
  names = {
    prefixes = { "gpt_neox.", "" },
    embed = "{p}embed_in.weight",
    final_norm = "{p}final_layer_norm.weight",
    lm_head = { "embed_out.weight" },
    pre_ff_norm = false,
    mlp_norm = "post_attention_layernorm.weight",
    q = false,
    k = false,
    v = false,
    qkv = "attention.query_key_value.weight",
    o = "attention.dense.weight",
    gate = false,
    up = "mlp.dense_h_to_4h.weight",
    down = "mlp.dense_4h_to_h.weight",
  },
  config = function(cfg, c)
    if cfg.use_parallel_residual == nil then c.parallel_residual = true end
  end,
}
