return {
  model_type = "gptj",
  llama_cpp = "gptj",
  verified = true,
  notes = "fixture: parallel residual with one LayerNorm, interleaved rotary over an absolute rotary_dim, fc_in/fc_out MLP with biases, lm_head bias. GPT-J 6B.",
  norm = "layer",
  parallel_residual = true,
  rope_style = "gptj",
  mlp = "dense",
  activation = "gelu_tanh",
  names = {
    prefixes = { "transformer.", "" },
    embed = "{p}wte.weight",
    final_norm = "{p}ln_f.weight",
    layer = "{p}h.{i}.",
    input_norm = { "ln_1.weight" },
    pre_ff_norm = false,
    q = "attn.q_proj.weight",
    k = "attn.k_proj.weight",
    v = "attn.v_proj.weight",
    o = "attn.out_proj.weight",
    gate = false,
    up = "mlp.fc_in.weight",
    down = "mlp.fc_out.weight",
  },
  config = require("gptj").config,
}
