return {
  model_type = "granitemoehybrid",
  llama_cpp = "granitehybrid",
  chat = "granite",
  verified = true,
  notes = "fixtures: Mamba2 and attention layers from layer_types (also the legacy mamba / attention names; the attention-only layout too), embedding / attention / residual / logits multipliers, fused input_linear / output_linear routed experts plus the fused shared_mlp, or a dense shared_mlp when num_local_experts is 0, optional RoPE (position_embedding_type). Granite 4.0 H (tiny, small).",
  positional = "none",
  mlp = "gated_fused",
  ssm = "mamba2",
  names = {
    prefixes = { "model.", "" },
    ssm = "mamba.",
    gate = false,
    up = false,
    gate_up = "shared_mlp.input_linear.weight",
    down = "shared_mlp.output_linear.weight",
    router = "block_sparse_moe.router.layer.weight",
    expert = "block_sparse_moe.experts.{e}.",
    expert_down = "output_linear.weight",
    fused_gate_up = { "block_sparse_moe.input_linear.weight" },
    fused_down = { "block_sparse_moe.output_linear.weight" },
    shared_expert = "shared_mlp.",
    shared_down = "output_linear.weight",
    shared_gate_up = "input_linear.weight",
  },
  hook = "granite_hybrid",
}
