return {
  model_type = "lfm2",
  llama_cpp = "lfm2",
  chat = "chatml",
  verified = true,
  notes = "fixture: gated short-convolution layers (in_proj B/C/x split, depthwise causal conv with conv_L_cache taps, out_proj) mixed with attention layers carrying per-head q/k norms, block_ff_dim sizing, embedding_norm as the final norm. LFM2 / LFM2.5 dense (lfm2_moe is unsupported).",
  default_norm_eps = 1e-5,
  tie_word_embeddings = true,
  qk_norm = "head",
  names = {
    final_norm = "{p}embedding_norm.weight",
    input_norm = { "operator_norm.weight" },
    pre_ff_norm = "ffn_norm.weight",
    q_norm = "self_attn.q_layernorm.weight",
    k_norm = "self_attn.k_layernorm.weight",
    o = "self_attn.out_proj.weight",
    gate = "feed_forward.w1.weight",
    up = "feed_forward.w3.weight",
    down = "feed_forward.w2.weight",
    conv_in = "conv.in_proj.weight",
    conv_kernel = "conv.conv.weight",
    conv_out = "conv.out_proj.weight",
  },
  hook = "lfm2",
}
