return {
  model_type = "minimax_m3_vl_text",
  aliases = { "minimax_m3_vl", "minimax_m3" },
  llama_cpp = "minimax-m3",
  verified = true,
  notes = "fixture: (1 + w) norms, per-head (1 + w) q/k norm, partial rotary, dense layers (mlp_layer_types) with a fused gate_up and the clamped swiglu, sigmoid MoE with correction bias, routed scaling and a fused-gate_up shared expert, minimax_m3_sparse layers run as dense attention (exact while the context fits index_topk_blocks blocks); the indexer weights pass through exports untouched. The image tower of the VL wrapper is never executed.",
  norm = "rms_gemma",
  mlp = "gated_fused",
  qk_norm = "head",
  names = {
    q_norm = "self_attn.q_norm.weight",
    k_norm = "self_attn.k_norm.weight",
    gate_up = "mlp.gate_up_proj.weight",
    router = "block_sparse_moe.gate.weight",
    router_correction_bias = "block_sparse_moe.e_score_correction_bias",
    expert = "block_sparse_moe.experts.{e}.",
    expert_gate = "w1.weight",
    expert_up = "w3.weight",
    expert_down = "w2.weight",
    fused_gate_up = {},
    fused_down = {},
    shared_expert = "block_sparse_moe.shared_experts.",
    shared_gate = "gate_proj.weight",
    shared_up = "up_proj.weight",
    shared_down = "down_proj.weight",
    shared_gate_up = "gate_up_proj.weight",
  },
  hook = "minimax_m3",
}
