return {
  model_type = "mpt",
  llama_cpp = "mpt",
  verified = true,
  notes = "fixture: ALiBi (alibi_bias_max), concatenated Wqkv, LayerNorm without bias, expansion_ratio.",
  norm = "layer",
  positional = "alibi",
  qkv = "concat",
  mlp = "dense",
  activation = "gelu",
  tie_word_embeddings = true,
  names = {
    prefixes = { "transformer.", "" },
    embed = "{p}wte.weight",
    final_norm = "{p}norm_f.weight",
    layer = "{p}blocks.{i}.",
    input_norm = { "norm_1.weight" },
    pre_ff_norm = "norm_2.weight",
    q = false,
    k = false,
    v = false,
    qkv = "attn.Wqkv.weight",
    o = "attn.out_proj.weight",
    gate = false,
    up = "ffn.up_proj.weight",
    down = "ffn.down_proj.weight",
  },
  hook = "mpt",
}
