return {
  model_type = "nemotron_h",
  llama_cpp = "nemotron_h",
  verified = true,
  notes = "fixture: one block per layer from hybrid_override_pattern / layers_block_type (M: Mamba2 with grouped gated norm and dt floor, *: attention without positional encoding, -: relu² MLP, E: non-gated experts with sigmoid group-limited routing, correction bias and a shared expert). Nemotron-H, Nemotron 3 Nano (llama.cpp: nemotron_h_moe).",
  default_norm_eps = 1e-5,
  positional = "none",
  mlp = "dense",
  activation = "relu2",
  ssm = "mamba2",
  single_mixer = true,
  names = {
    prefixes = { "backbone.", "" },
    embed = "{p}embeddings.weight",
    final_norm = "{p}norm_f.weight",
    input_norm = { "norm.weight" },
    pre_ff_norm = false,
    q = "mixer.q_proj.weight",
    k = "mixer.k_proj.weight",
    v = "mixer.v_proj.weight",
    o = "mixer.o_proj.weight",
    ssm = "mixer.",
    gate = false,
    up = "mixer.up_proj.weight",
    down = "mixer.down_proj.weight",
    router = "mixer.gate.weight",
    router_correction_bias = "mixer.gate.e_score_correction_bias",
    expert = "mixer.experts.{e}.",
    fused_gate_up = {},
    fused_down = {},
    shared_expert = "mixer.shared_experts.",
  },
  hook = "nemotron_h",
}
