return {
  model_type = "opt",
  llama_cpp = nil,
  verified = true,
  notes = "fixture: learned positions with offset 2, ReLU, LayerNorm biases. Pre-norm variants only (OPT-350m's projection layers are unsupported).",
  norm = "layer",
  positional = "learned",
  mlp = "dense",
  activation = "relu",
  attention_bias = true,
  tie_word_embeddings = true,
  names = {
    prefixes = { "model.decoder.", "decoder." },
    pos_embed = "{p}embed_positions.weight",
    final_norm = "{p}final_layer_norm.weight",
    input_norm = { "self_attn_layer_norm.weight" },
    pre_ff_norm = "final_layer_norm.weight",
    o = "self_attn.out_proj.weight",
    gate = false,
    up = "fc1.weight",
    down = "fc2.weight",
  },
  hook = "opt",
}
