return {
  model_type = "qwen4_exp",
  aliases = { "qwen4_exp_text" },
  llama_cpp = nil,
  chat = "chatml",
  verified = true,
  notes = "fixture: Qwen3.8-Flash-Next text config under the multimodal wrapper: gated hyper-connections (hc_count streams, (1 + w) group norms, low-rank sigmoid input mixer, sigmoid injection weights, no final norm), Gated DeltaNet layers with a sigmoid or silu output gate, sigmoid-gated full attention with (1 + w) head norms and partial rotary behind a QSA indexer (run as dense: exact while every complete block fits indexer_budget, longer prompts refused), per-layer n-gram embeddings (PLE: splitmix64 hash multipliers, prime bucket ranges, sharded tables read row by row, gated values, dilated depthwise convolution), fused softmax MoE with a gated shared expert on every layer. Vision and indexer tensors pass through exports untouched.",
  norm = "rms_gemma",
  qk_norm = "head",
  names = {
    final_norm = false,
    input_norm = {},
    pre_ff_norm = false,
    q_norm = "self_attn.q_norm.weight",
    k_norm = "self_attn.k_norm.weight",
    lin_qkv = "linear_attn.in_proj_qkv.weight",
    lin_z = "linear_attn.in_proj_z.weight",
    lin_b = "linear_attn.in_proj_b.weight",
    lin_a = "linear_attn.in_proj_a.weight",
    lin_conv = "linear_attn.conv1d.weight",
    lin_dt_bias = { "linear_attn.dt_bias" },
    lin_a_log = { "linear_attn.A_log" },
    lin_norm = "linear_attn.norm.weight",
    lin_out = "linear_attn.out_proj.weight",
    shared_expert = "mlp.shared_expert.",
    shared_expert_gate = "mlp.shared_expert_gate.weight",
    hc_attn = "attn_hyper_connection",
    hc_ffn = "mlp_hyper_connection",
    hc_attn_flat = false,
    hc_ffn_flat = false,
  },
  hook = "qwen4_exp",
}
