return {
  model_type = "qwen3_5_moe",
  aliases = { "qwen3_5_moe_text" },
  llama_cpp = nil,
  chat = "qwen3_5",
  verified = true,
  notes = "fixture: split-projection linear layers with a swish output gate, fused softmax MoE with shared expert.",
  norm = "rms_gemma",
  qk_norm = "head",
  names = {
    q_norm = "self_attn.q_norm.weight",
    k_norm = "self_attn.k_norm.weight",
    lin_qkv = "linear_attn.in_proj_qkv.weight",
    lin_z = "linear_attn.in_proj_z.weight",
    lin_b = "linear_attn.in_proj_b.weight",
    lin_a = "linear_attn.in_proj_a.weight",
    lin_conv = "linear_attn.conv1d.weight",
    lin_dt_bias = { "linear_attn.dt_bias" },
    lin_a_log = { "linear_attn.A_log" },
    lin_norm = "linear_attn.norm.weight",
    lin_out = "linear_attn.out_proj.weight",
    shared_expert = "mlp.shared_expert.",
    shared_expert_gate = "mlp.shared_expert_gate.weight",
  },
  hook = "qwen_hybrid",
}
